export const ERROR_CODES = {
    UNAUTHORIZED: 'UNAUTHORIZED',
    MISSING_FIELDS: 'MISSING_FIELDS',
    MISSING_CREDENTIALS: 'MISSING_CREDENTIALS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    INVALID_EMAIL: 'INVALID_EMAIL',
    PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    INVALID_GAME_PAYLOAD: 'INVALID_GAME_PAYLOAD',
    INVALID_CHARACTER_PAYLOAD: 'INVALID_CHARACTER_PAYLOAD',
    INVALID_PAYLOAD: 'INVALID_PAYLOAD',
    MISSING_ID: 'MISSING_ID',
    GAME_NOT_FOUND: 'GAME_NOT_FOUND',
    CHARACTER_NOT_FOUND: 'CHARACTER_NOT_FOUND'
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
